site_name: Carbyne
theme_dir: 'mkdocs-material/material'
repo_name: 'GitHub'
repo_url: 'https://github.com/ceymard/carbyne'

pages:
  - index.md
  - API:
    - 'Atom': api/atom.md
    - 'Observable': api/observable.md

extra:
  version: 0.1.1
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
